puts require 'active_support'
require 'tapi/v3/configurable'
require 'tapi/v3/errors'
require 'tapi/v3/client'
require 'tapi/v3/validations'
require 'tapi/v3/utils'
require 'tapi/v3/generic_search'
require 'tapi/v3/hotels/search'
require 'tapi/v3/flights/search'
